"""add admission consulting report

Revision ID: 1c722f5f3e76
Revises: 368c5d0bce36
Create Date: 2026-08-08 04:36:42.346339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c722f5f3e76'
down_revision: Union[str, Sequence[str], None] = '368c5d0bce36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'student_profiles',
        sa.Column(
            'admission_report',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column('student_profiles', 'admission_report', server_default=None)
    op.add_column('student_profiles', sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'report_generated_at')
    op.drop_column('student_profiles', 'admission_report')
    # ### end Alembic commands ###
