"""add academic record summary

Revision ID: 368c5d0bce36
Revises: ab36885a3af2
Create Date: 2026-08-08 04:03:19.170524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '368c5d0bce36'
down_revision: Union[str, Sequence[str], None] = 'ab36885a3af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'student_profiles',
        sa.Column(
            'academic_record',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column('student_profiles', 'academic_record', server_default=None)
    op.add_column('student_profiles', sa.Column('record_processed_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'record_processed_at')
    op.drop_column('student_profiles', 'academic_record')
    # ### end Alembic commands ###
