"""add profile survey answers

Revision ID: ab36885a3af2
Revises: 53f9ed4602db
Create Date: 2026-08-08 03:43:02.295942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab36885a3af2'
down_revision: Union[str, Sequence[str], None] = '53f9ed4602db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'student_profiles',
        sa.Column(
            'survey_answers',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column('student_profiles', 'survey_answers', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'survey_answers')
    # ### end Alembic commands ###
